"""empty message

Revision ID: d0df6fdc6515
Revises: c412cb80b401
Create Date: 2022-02-20 14:47:05.037492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0df6fdc6515'
down_revision = 'c412cb80b401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ports', sa.Column('url', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ports', 'url')
    # ### end Alembic commands ###
